config/routes.rb
TufcSite::Application.routes.draw do

  root :to => 'pages#home'

  resources :subscribers, :only =>[:new,:index,:create,:destroy]

  resources :games
  resources :newsletters

  resources :players do
    resources :stats
  end

  match '/about', :to => 'pages#about'
  match '/contact', :to => 'contact_mailer#index'
  match '/sendmail', :to => 'contact_mailer#sendmail'

  resources :sessions, :only => [:new, :create, :destroy]
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/newsletter.rb
# == Schema Information
#
# Table name: newsletters
#
#  id          :integer         not null, primary key
#  entry       :text
#  created_at  :datetime
#  updated_at  :datetime
#  authored_by :string(255)
#

class Newsletter < ActiveRecord::Base

end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController

  before_filter :authenticate, :only =>[:edit,:new,:create,:update,:destroy]

  # GET /newsletters
  def index
    @newsletters = Newsletter.order('created_at DESC').paginate(:page => params[:page],:per_page => 3)
  end

  # GET /newsletters/1
  def show
    @newsletter = Newsletter.find(params[:id])
  end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
  end

  # GET /newsletters/1/edit
  def edit
    @newsletter = Newsletter.find(params[:id])
  end

  # POST /newsletters
  def create
    @newsletter = Newsletter.new(params[:newsletter])
    if @newsletter.save
      flash[:success] = 'Newsletter Successfully created'
      redirect_to @newsletter
    else
      flash[:error] = 'There was a problem creating your newsletter.'
      redirect_to newsletters_path
    end
  end

  # PUT /newsletters/1
  def update
    @newsletter = Newsletter.find(params[:id])
    @newsletter.update_attributes(params[:newsletter])
    if @newsletter.save
      flash[:success] = 'Newsletter update successful.'
      redirect_to @newsletter
    else
      flash[:error] = 'Something went wrong when updating this newsletter'
      redirect_to edit_newsletter_path(@newsletter.id)
    end
  end

  # DELETE /newsletters/1
  def destroy
    @newsletter = Newsletter.find(params[:id])
    if @newsletter.destroy
      flash[:success] = 'Newsletter Successfully Removed'
      redirect_to newsletters_path
    else
      flash[:error] = 'Something went wrong when deleting this newsletter'
      redirect_to newsletters_path
    end

  end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/newsletters/_newsletter.html.erb
<% if (newsletter.id == Newsletter.last.id)%>
<% else %>
<hr>
<% end %>
<h1><%= newsletter.updated_at.strftime('Created on %b %d,%Y') %></h1>
<%= raw(BlueCloth.new(newsletter.entry).to_html) %> <hr class="space" />
<% if signed_in? %>
<hr class="space" />
<%= link_to 'Edit This Entry', edit_newsletter_path(newsletter.id) %><br />
<%= link_to 'Delete This Entry', newsletter_path(newsletter.id), :method => :delete %>
<% end %>

app/views/newsletters/edit.html.erb
<div class="prepend-8 span-8 append-8 last">
<%= form_for @newsletter do |f| %>
  <%= render 'shared/error_messages', :object => @newsletter %>
  <%= f.text_area :entry, :class => 'jq_watermark', :title => 'Newsletter Entry' %>
  <br />
  This box accepts <%= link_to 'Markdown', 'http://en.wikipedia.org/wiki/Markdown' %>.
  <hr class="space" />
  <%= f.text_field :authored_by, :class => 'jq_watermark',:title => 'Your Name' %><hr class="space" />
  <%= f.submit 'Edit Entry' %>
<% end %>
</div>

app/views/newsletters/index.html.erb
<div class="prepend-4 span-16 append-4 last">
<%= render @newsletters %><br />
<div class="prepend-6 span-7" id="paginate-information">
<hr class="space" />
<hr class="space" />
<%= will_paginate @newsletters %>
<%= raw(page_entries_info @newsletters) %>
</div>
</div>

app/views/newsletters/new.html.erb
<div class="prepend-2 span-14 append-8 last">
<%= form_for @newsletter do |f| %>
  <%= render 'shared/error_messages', :object => @newsletter %>
  <%= f.text_area :entry, :class => 'jq_watermark', :title => 'Newsletter Entry' %>
  <br />
  This box accepts <%= link_to 'Markdown', 'http://en.wikipedia.org/wiki/Markdown' %>.
  <hr class="space" />
  <%= f.text_field :authored_by, :class => 'jq_watermark',:title => 'Your Name' %><hr class="space" />
  <%= f.submit 'Create Entry' %>
<% end %>
</div>

app/views/newsletters/show.html.erb
<div class="prepend-2 span-20 append-2 last">
<%= render @newsletter %>
</div>