config/routes.rb
TufcSite::Application.routes.draw do

  root :to => 'pages#home'

  resources :subscribers, :only =>[:new,:index,:create,:destroy]

  resources :games
  resources :newsletters

  resources :players do
    resources :stats
  end

  match '/about', :to => 'pages#about'
  match '/contact', :to => 'contact_mailer#index'
  match '/sendmail', :to => 'contact_mailer#sendmail'

  resources :sessions, :only => [:new, :create, :destroy]
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id='error_explanation' >
    <h2>
    <%= pluralize(object.errors.count, "error") %>
    prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from bieng saved:
    </h2>
    <p> There were problems with the following fields: </p>
    <ul>
    <% object.errors.full_messages.each do |message|%>
    <li><%= message %></li>
    <% end %>
    </ul>
  </div>

<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |key,value| %>
<div class="flash <%= key %> span-22 last prepend-1">
<%= value %>
</div>
<% end %>

app/views/shared/_footer.html.erb
<head>
<%= stylesheet_link_tag 'custom/footer', :media => :screen %>
</head>

<div class="span-24 last" id="footer-wrapper">
<div class="prepend-1 span-8 column" id="facebook-links">
<%= link_to image_tag('facebook_32.png'), 'http://www.facebook.com/pages/TUFC-Venom/86854084508', :target => '_blank',:align => 'center' %>
<br /> ©<%= Time.now.year %>, by <%= link_to 'Taylor Perkins', 'http://hwrdprkns.com', :target => '_blank' %>
</div>


<% if signed_in? %>
<div class="prepend-5 span-9 apprend-1 last column" id="site-links">
<%= link_to 'Subscribers', subscribers_path %>
<%= link_to 'Create Player', new_player_path %>
<%= link_to 'Create Game', new_game_path %>
<%= link_to 'Create Newsletter', new_newsletter_path %>
<%= link_to 'Sign Out', '/signout' %>
</div>
<% else %>
<div class="prepend-11 span-3 append-1 last column" id="site-links">
<%= link_to 'Sitemap', '/sitemap1.xml.gz' %>
<%= link_to 'Sign In', '/signin' %>
</div>
<% end %>
</div>

app/views/shared/_header.html.erb
<head>
<%= stylesheet_link_tag 'custom/header', :media => :screen %>
</head>

<div class="span-24 last" id="header-wrapper">
<br />
<div id="logo" class="span-6 prepend-1">
<h1><%= link_to image_tag('logo.jpg', :size=>'250x75'), root_path %></h1>
</div>
<div class="span-16 last" id="nav-links">
<h2 class="span-3 append-1"><%= link_to 'ROSTERS', players_path %></h2>
<h2 class="span-3"><%= link_to 'ABOUT', '/about' %></h2>
<h2 class="span-3"><%= link_to 'NEWS', newsletters_path %></h2>
<h2 class="span-3"><%= link_to 'GAMES', games_path %></h2>
<h2 class="span-3 last"><%= link_to 'CONTACT', '/contact' %></h2>
</div>
</div>

app/views/shared/_javascripts.html.erb
<%= javascript_include_tag :defaults %>
<%= javascript_include_tag 'jquery.watermark.min.js' %>

app/views/shared/_stylesheets.html.erb
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<%= stylesheet_link_tag 'custom/errors', :media => 'screen' %>

<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->