config/routes.rb
TufcSite::Application.routes.draw do

  root :to => 'pages#home'

  resources :subscribers, :only =>[:new,:index,:create,:destroy]

  resources :games
  resources :newsletters

  resources :players do
    resources :stats
  end

  match '/about', :to => 'pages#about'
  match '/contact', :to => 'contact_mailer#index'
  match '/sendmail', :to => 'contact_mailer#sendmail'

  resources :sessions, :only => [:new, :create, :destroy]
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id            :integer         not null, primary key
#  date          :datetime
#  against       :string(255)
#  tufc_goals    :integer
#  against_goals :integer
#  home          :boolean
#  league_game   :boolean
#  playoff_game  :boolean
#  created_at    :datetime
#  updated_at    :datetime
#

class Game < ActiveRecord::Base

  validates_presence_of :date
  validates_presence_of :against

  default_scope :order => 'games.date DESC'

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_filter :authenticate, :only =>[:edit,:new,:create,:update,:destroy]

  # GET /games
  def index
    @games = Game.order('date DESC').paginate(:page => params[:page],:per_page => 20)
  end

  # GET /games/1
  def show
   @game = Game.find(params[:id])
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  def create
    date = DateTime.civil_from_format('utc',params[:date][:year].to_i,params[:date][:month].to_i,params[:date][:day].to_i)
    params[:game][:date]=date.to_datetime
    #raise params.inspect
    @game = Game.new(params[:game])
     if params[:game][:against].blank?
       flash[:notice]='You must fill out all fields'
       redirect_to new_game_path
       return
     end

     if @game.save
       flash[:success] = 'Game successfully created!'
       redirect_to @game
     else
       flash[:error] = 'Something went wrong with creating your game! Try again!'
       redirect_to new_game_path
     end
  end

  # PUT /games/1
  def update
    @game = Game.find(params[:id])
    if @game.update_attributes(params[:game])
      flash[:notice]='Game updated successfully'
      redirect_to @game
    else
      flash[:error]='Something went wrong when updating that game'
      redirect_to edit_game_path(@game)
    end
  end

  # DELETE /games/1
  def destroy
    @game = Game.find(params[:id])
    if @game.destroy
      flash[:success] = 'Game successfully deleted'
      redirect_to games_path
    else
      flash[:error]='Something went wrong when deleting that game'
      redirect_to edit_game_path(@game)
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper

  def normalize(bool)
    if bool
      return 'Yes'
    else
      return 'No'
    end
  end

end

app/views/games/_game.html.erb
<% if signed_in? %>
<td><%= link_to 'Edit', edit_game_path(game) %>&#x9;|&#x9;<%= link_to 'Delete', game_path(game), :method => :delete %></td>
<% end %>
<td><%= game.date.strftime('%b %d, %Y') %></td>
<td><%= game.against %></td>
<td><%= game.tufc_goals %></td>
<td><%= game.against_goals %></td>
<td><%= normalize(game.league_game) %></td>
<td><%= win_or_loss(game) %></td>

app/views/games/edit.html.erb
<div id="form-inputs" class="prepend-6 span-12 append-6 last">
<% form_for @game do |f| %>
  <%= render 'shared/error_messages', :object => @game %>
 Game Date: <%= select_datetime(Time.current,:order=>[:year,:month,:day]) %><br />
 Against: <%= f.text_field :against, :title => "Against",:class =>'jq_watermark' %><br />
 TUFC Goals: <%= f.number_field :tufc_goals,:value => '1', :title => "TUFC Goals",:class =>'jq_watermark' %><br />
 Against Goals: <%= f.number_field :against_goals,:value =>'0', :title => "Against Goals",:class =>'jq_watermark' %><br />
 League Game? <%= f.check_box :league_game, :title => "Against",:class =>'jq_watermark' %><br />
 <hr class="space" />
 <%= f.submit 'Edit Game' %>
<% end %>
</div>

app/views/games/index.html.erb
<h1>Games</h1>
<% if @games.size == 0 %>
<div class="prepend-9 span-6 append-9 last">
Sorry, there are no recent games to show!
</div>
<% else %>
<div class="span-24 last">
<table border="1"">
<tr>
<% if signed_in? %>
<td></td>
<% end %>
<td><b>Date</b></td>
<td><b>Against</b></td>
<td><b>TUFC Goals</b></td>
<td><b>Opponent Goals</b></td>
<td><b>League Game</b></td>
<td><b>Result</b></td>
</tr>
<% @games.each do |game| %>
<tr>
<%= render 'game', :game => game %>
<% end %>
</tr>
</table>
<div class="prepend-10 span-7" id="paginate-information">
<hr class="space" />
<hr class="space" />
<%= will_paginate @games %>
<%= raw(page_entries_info @games) %>
</div>
</div>
<% end %>

app/views/games/new.html.erb
<div id="form-inputs" class="prepend-6 span-12 append-6 last">
<% form_for @game do |f| %>
 <%= render 'shared/error_messages', :object => @game %>
 Game Date: <%= select_datetime(Time.current,:order=>[:year,:month,:day]) %><br />
 Against: <%= f.text_field :against, :title => "Against",:class =>'jq_watermark' %><br />
 TUFC Goals: <%= f.number_field :tufc_goals,:value => '1', :title => "TUFC Goals",:class =>'jq_watermark' %><br />
 Against Goals: <%= f.number_field :against_goals,:value =>'0', :title => "Against Goals",:class =>'jq_watermark' %><br />
 League Game? <%= f.check_box :league_game, :title => "Against",:class =>'jq_watermark' %><br />
 <hr class="space" />
 <%= f.submit 'Create Game' %>
<% end %>
</div>

app/views/games/show.html.erb
<div class="prepend-1 span-22 append-1 last">
<table border="1"">
<tr>
<% if signed_in? %>
<hr class="space" />
<td></td>
<% end %>
<td><b>Date</b></td>
<td><b>Against</b></td>
<td><b>TUFC Goals</b></td>
<td><b>Opponent Goals</b></td>
<td><b>League Game</b></td>
<td><b>Result</b></td>
</tr>
<%= render @game %>
</tr>
</table>
<% if signed_in? %>
<hr class="space" />
<%= link_to 'Edit This Game', edit_game_path(@game.id) %><br />
<%= link_to 'Delete This Game', game_path(@game.id), :method => :delete %>
<% end %>
</div>