config/routes.rb
TufcSite::Application.routes.draw do

  root :to => 'pages#home'

  resources :subscribers, :only =>[:new,:index,:create,:destroy]

  resources :games
  resources :newsletters

  resources :players do
    resources :stats
  end

  match '/about', :to => 'pages#about'
  match '/contact', :to => 'contact_mailer#index'
  match '/sendmail', :to => 'contact_mailer#sendmail'

  resources :sessions, :only => [:new, :create, :destroy]
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id                 :integer         not null, primary key
#  first_team         :boolean
#  preffered_position :string(255)
#  rating             :integer
#  hometown           :string(255)
#  notes              :text
#  first_name         :string(255)
#  last_name          :string(255)
#  year               :integer
#  created_at         :datetime
#  updated_at         :datetime
#  email              :string(255)
#

class Player < ActiveRecord::Base
  has_many :stats, :dependent => :destroy

  validates :first_name, :presence => true, :length => {:maximum => 50}
  validates :last_name, :presence => true
  validates :email, :presence => true, :format => {:with => /^([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})$/i}, :uniqueness => {:case_sensitive => false}
  validates :year, :presence => true
  validates_numericality_of :year, :greater_than => 1950, :less_than => 2100
  validates_numericality_of :rating, :greater_than => 0, :less_than => 11

  default_scope :order => 'last_name'





end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.xml
  def index
    @aTeam = Player.where('first_team = ? AND year > ?',true,Time.now.year)
    @bTeam = Player.where('first_team = ? AND year > ?',false,Time.now.year)
    @fullRoster = Player.where('year > ?',Time.now.year)
    @legends = Player.where('year <= ?',Time.now.year)
  end

  # GET /players/1
  # GET /players/1.xml
  def show
    @player = Player.find(params[:id])
  end

  # GET /players/new
  # GET /players/new.xml
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.xml
  def create
    @player = Player.new(params[:player])
    if @player.save
      redirect_to @player, :flash => {:success => 'Player creation successful'}
    else
      render 'new'
    end
  end

  # PUT /players/1
  # PUT /players/1.xml
  def update
    @player = Player.find(params[:id])
    @player.update_attributes(params[:player])
    if @player.save
      flash[:success] = 'Player updated!'
      redirect_to @player
    else
      flash[:error]='Something went wrong. Please try again.'
      redirect_to @player
    end
  end

  # DELETE /players/1
  # DELETE /players/1.xml
  def destroy
    @player = Player.find(params[:id])
    if @player.destroy
      flash[:success] = 'Player deleted!'
      redirect_to players_path
    else
      flash[:error]='Something went wrong. Please try again.'
      redirect_to players_path
    end

  end
end

app/helpers/players_helper.rb
module PlayersHelper

  def hometown(player)
    if player.hometown.blank?
      return 'Unknown'
    else
      return player.hometown
    end
  end

  def header_name(player)
    return player.first_name + ' ' + player.last_name + '(' + player.year.to_s + ')'
  end

  def preffered_position(player)
    if player.preffered_position.blank?
      return 'No preffered position'
    end
    return 'Position(s): '+player.preffered_position
  end

  def rating(player)
    if player.rating.blank?
      return 'Player not rated'
    end
    return 'Player Rating(1 to 10): '+player.rating.to_s
  end

  def first_team(player)
    if player.first_team
      return 'This player is currently on the A team!'
    else
      return 'This player is currently on the B team!'
    end
  end

  def individual_preffered_position(player)
    if player.preffered_position.blank?
      return 'None'
    else
      return player.preffered_position
    end
  end

  def team(player)
    if player.first_team
      return 'A'
    else
      return 'B'
    end
  end

end

app/views/players/_aPlayer.html.erb
<!-- Continuing the table set in _playerTable.html.erb -->

  <tr>
    <% if signed_in? %>
    <td><%= link_to 'Edit', edit_player_path(aPlayer) %>&#x9;|&#x9;<%= link_to 'Delete', player_path(aPlayer),:method=> :delete %></td>
    <% end %>
    <td><%= link_to header_name(aPlayer), player_path(aPlayer) %></td>
    <td><%= hometown aPlayer %></td>
    <td><%= individual_preffered_position aPlayer %></td>
  </tr>

app/views/players/_aTeam.html.erb
<% @aTeam.each do |aPlayer| %>

<%= render 'aPlayer', :aPlayer => aPlayer %>

<% end %>

app/views/players/_bTeam.html.erb
<% @bTeam.each do |bPlayer| %>

<%= render 'aPlayer', :aPlayer => bPlayer %>

<% end %>

app/views/players/_fullPlayer.html.erb
<!-- Continuing the table set in _playerTable.html.erb -->

  <tr>
    <% if signed_in? %>
    <td><%= link_to 'Edit', edit_player_path(aPlayer) %>&#x9;|&#x9;<%= link_to 'Delete', player_path(aPlayer),:method=> :delete %></td>
    <% end %>
    <td><%= link_to header_name(aPlayer), player_path(aPlayer) %></td>
    <td><%= hometown aPlayer %></td>
    <td><%= individual_preffered_position aPlayer %></td>
    <td><%= team aPlayer %>
  </tr>

app/views/players/_fullRoster.html.erb
<% @fullRoster.each do |player| %>

<%= render 'fullPlayer', :aPlayer => player %>

<% end %>

app/views/players/_fullTable.html.erb
<table>
  <tr>
    <% if signed_in? %>
      <td></td>
    <% end %>
    <td>Name(Year)</td>
    <td>Hometown</td>
    <td>Position(s)</td>
    <td>Team Status</td>
  </tr>

app/views/players/_legends.html.erb
<% @legends.each do |legend| %>

<%= render 'aPlayer', :aPlayer => legend %>

<% end %>

app/views/players/_player.html.erb
<h1>Player View </h1>
<hr class="space" />
<div id="header-info" class="prepend-1 span-12 append-1 last">
<span class="loud large"><%= header_name @player %></span>
<hr class="space" />
<span class="loud">Hometown:
<%= hometown @player %>
</span>
<hr class="space" />
<span class="quiet">Notes:
<%= hometown @player %>
</span>
</div>

<div id="player-info" class="prepend-1 span-8 append-1 last">
<%= preffered_position @player %><hr class="space"  />
<%= rating @player %><hr class="space" />
<%= first_team @player %><hr class="space" />
</div>

<hr class="space" />

<h1>Stats for <%= @player.first_name + ' ' + @player.last_name %></h1>

<div class="prepend-2 span-20 append-2 last" id="stat-container">

<% if @player.stats.empty? %>
<h2> There are no stats to show for this player yet.</h2>
<% else %>
<table>
  <tr>
  <% if signed_in? %>
    <td></td>
  <% end %>

    <td>Season</td>
    <td>Goals</td>
    <td>Assists</td>
    <td>Yellow/Red Cards</td>
    <td>Games Played</td>
    <td>Eboard Position</td>
  </tr>
<% @player.stats.each do |stat| %>
<%= render stat %>
<% end %>
</table>
<% end %>
</div>

<hr class="space" />
<% if signed_in? %>
<%= link_to '(Create New Stat)', new_player_stat_path(@player) %>
<% end %>

app/views/players/_playerTable.html.erb
<table>
  <tr>
    <% if signed_in? %>
      <td></td>
    <% end %>
    <td>Name(Year)</td>
    <td>Hometown</td>
    <td>Position(s)</td>
  </tr>

app/views/players/edit.html.erb
<h1>Create Player </h1>
<% form_for @player do |f| %>
  <%= render 'shared/error_messages', :object => @player %>

  <div id="personal info" class="span-12">
  <h2>Personal Information</h2>
  <%= f.label :hometown %><br />
  <%= f.text_field :hometown %><br />
  <%= f.label :notes %><br />
  <%= f.text_area :notes %><br />
  This box accepts <%= link_to 'Markdown', 'http://en.wikipedia.org/wiki/Markdown' %><br />
  <%= f.label :first_name %><br />
  <%= f.text_field :first_name %><br />
  <%= f.label :last_name %><br />
  <%= f.text_field :last_name %><br />
  <%= f.label :year, 'Class Of' %><br />
  <%= f.number_field :year %><br />
  <%= f.label :email %><br />
  <%= f.text_field :email %>
  </div>
  <div id="player-info" class="span-12 last">
  <h2>Player Information</h2>
  <%= f.label :first_team, 'First Team?' %><br />
  <%= f.check_box :first_team %><hr class="space" />

  <%= f.label :preffered_position %><br />
  <%= f.text_field :preffered_position %><hr class="space" />

  <%= f.label :rating, 'Rating(Between 1 and 10)' %><br />
  <%= f.number_field :rating %><hr class="space" />
  </div>

  <%= f.submit %>
<% end %>

app/views/players/index.html.erb
<head>
<%= javascript_include_tag 'jquery.hashchange.js' %>
<%= javascript_include_tag 'jquery.easytabs.min.js' %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#tab-container').easytabs();
  });
</script>

<%= stylesheet_link_tag 'custom/playerIndex', :media => 'screen' %>

</head>

<h1>Current Rosters </h1>

<div class="prepend-1 span-22 append-1 last">

  <div id="tab-container" class="span-22">

    <ul class="">
      <li><a href="#a-team-div">A Team</a></li>
      <li><a href="#b-team-div">B Team</a></li>
      <li><a href="#full-roster-div">Full Roster</a></li>
      <li><a href="#legends-div">Alumni</a></li>
      <br style="clear:both;" />
    </ul>

  <div class="panel-container">
    <div id="a-team-div" class="prepend-1">
      <%= render 'playerTable' %>
      <%= render 'aTeam' %>
      </table>
    </div>
    <div id="b-team-div" class="prepend-1">
    <%= render 'playerTable' %>
    <%= render 'bTeam' %>
    </table>
     </div>
    <div id="full-roster-div" class="prepend-1">
      <%= render 'fullTable' %>
      <%= render 'fullRoster' %>
      </table>
    </div>
    <div id="legends-div" class="prepend-1">
      <%= render 'playerTable' %>
      <%= render 'legends' %>
      </table>
    </div>
  </div>
</div>
</div>

app/views/players/new.html.erb
<h1>Create Player </h1>
<% form_for @player do |f| %>
  <%= render 'shared/error_messages', :object => @player %>

  <div id="personal info" class="span-12">
  <h2>Personal Information</h2>
  <%= f.label :hometown %><br />
  <%= f.text_field :hometown %><br />
  <%= f.label :notes %><br />
  <%= f.text_area :notes %><br />
  This box accepts <%= link_to 'Markdown', 'http://en.wikipedia.org/wiki/Markdown' %><br />
  <%= f.label :first_name %><br />
  <%= f.text_field :first_name %><br />
  <%= f.label :last_name %><br />
  <%= f.text_field :last_name %><br />
  <%= f.label :year, 'Class Of' %><br />
  <%= f.number_field :year, :value => 2012 %><br />
  <%= f.label :email %><br />
  <%= f.text_field :email %>
  </div>
  <div id="player-info" class="span-12 last">
  <h2>Player Information</h2>
  <%= f.label :first_team, 'First Team?' %><br />
  <%= f.check_box :first_team %><hr class="space" />

  <%= f.label :preffered_position %><br />
  <%= f.text_field :preffered_position %><hr class="space" />

  <%= f.label :rating, 'Rating(Between 1 and 10)' %><br />
  <%= f.number_field :rating %><hr class="space" />
  </div>

  <%= f.submit %>
<% end %>

app/views/players/show.html.erb
<%= render @player %>